# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.proto import customer_pb2 as customer__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in customer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CustomerServiceStub(object):
    """-------------------------------------------------
    Customer Service Definition
    -------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAccount = channel.unary_unary(
                '/customer.CustomerService/CreateAccount',
                request_serializer=customer__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=customer__pb2.CreateAccountResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/customer.CustomerService/Login',
                request_serializer=customer__pb2.LoginRequest.SerializeToString,
                response_deserializer=customer__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/customer.CustomerService/Logout',
                request_serializer=customer__pb2.SessionRequest.SerializeToString,
                response_deserializer=customer__pb2.Empty.FromString,
                _registered_method=True)
        self.ValidateSession = channel.unary_unary(
                '/customer.CustomerService/ValidateSession',
                request_serializer=customer__pb2.SessionRequest.SerializeToString,
                response_deserializer=customer__pb2.SessionInfo.FromString,
                _registered_method=True)
        self.GetSellerRating = channel.unary_unary(
                '/customer.CustomerService/GetSellerRating',
                request_serializer=customer__pb2.SessionSellerRequest.SerializeToString,
                response_deserializer=customer__pb2.RatingResponse.FromString,
                _registered_method=True)
        self.RecordSellerFeedback = channel.unary_unary(
                '/customer.CustomerService/RecordSellerFeedback',
                request_serializer=customer__pb2.RecordSellerFeedbackRequest.SerializeToString,
                response_deserializer=customer__pb2.Empty.FromString,
                _registered_method=True)
        self.GetBuyerPurchases = channel.unary_unary(
                '/customer.CustomerService/GetBuyerPurchases',
                request_serializer=customer__pb2.SessionRequest.SerializeToString,
                response_deserializer=customer__pb2.PurchaseList.FromString,
                _registered_method=True)
        self.RecordPurchase = channel.unary_unary(
                '/customer.CustomerService/RecordPurchase',
                request_serializer=customer__pb2.RecordPurchaseRequest.SerializeToString,
                response_deserializer=customer__pb2.Empty.FromString,
                _registered_method=True)
        self.Barrier = channel.unary_unary(
                '/customer.CustomerService/Barrier',
                request_serializer=customer__pb2.BarrierRequest.SerializeToString,
                response_deserializer=customer__pb2.Empty.FromString,
                _registered_method=True)


class CustomerServiceServicer(object):
    """-------------------------------------------------
    Customer Service Definition
    -------------------------------------------------

    """

    def CreateAccount(self, request, context):
        """-------- Account APIs --------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSession(self, request, context):
        """-------- Session Validation --------
        Called by Product DB to validate a session token
        without needing to share in-memory state.
        This is the key to making separate VM processes work.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerRating(self, request, context):
        """-------- Ratings --------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordSellerFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuyerPurchases(self, request, context):
        """-------- Purchases --------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordPurchase(self, request, context):
        """-------- Purchase Recording --------
        Called by Product DB after finalizing a purchase
        so buyer purchase history is recorded in Customer DB

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Barrier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=customer__pb2.CreateAccountRequest.FromString,
                    response_serializer=customer__pb2.CreateAccountResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=customer__pb2.LoginRequest.FromString,
                    response_serializer=customer__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=customer__pb2.SessionRequest.FromString,
                    response_serializer=customer__pb2.Empty.SerializeToString,
            ),
            'ValidateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSession,
                    request_deserializer=customer__pb2.SessionRequest.FromString,
                    response_serializer=customer__pb2.SessionInfo.SerializeToString,
            ),
            'GetSellerRating': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerRating,
                    request_deserializer=customer__pb2.SessionSellerRequest.FromString,
                    response_serializer=customer__pb2.RatingResponse.SerializeToString,
            ),
            'RecordSellerFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordSellerFeedback,
                    request_deserializer=customer__pb2.RecordSellerFeedbackRequest.FromString,
                    response_serializer=customer__pb2.Empty.SerializeToString,
            ),
            'GetBuyerPurchases': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyerPurchases,
                    request_deserializer=customer__pb2.SessionRequest.FromString,
                    response_serializer=customer__pb2.PurchaseList.SerializeToString,
            ),
            'RecordPurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordPurchase,
                    request_deserializer=customer__pb2.RecordPurchaseRequest.FromString,
                    response_serializer=customer__pb2.Empty.SerializeToString,
            ),
            'Barrier': grpc.unary_unary_rpc_method_handler(
                    servicer.Barrier,
                    request_deserializer=customer__pb2.BarrierRequest.FromString,
                    response_serializer=customer__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'customer.CustomerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('customer.CustomerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomerService(object):
    """-------------------------------------------------
    Customer Service Definition
    -------------------------------------------------

    """

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerService/CreateAccount',
            customer__pb2.CreateAccountRequest.SerializeToString,
            customer__pb2.CreateAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerService/Login',
            customer__pb2.LoginRequest.SerializeToString,
            customer__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerService/Logout',
            customer__pb2.SessionRequest.SerializeToString,
            customer__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerService/ValidateSession',
            customer__pb2.SessionRequest.SerializeToString,
            customer__pb2.SessionInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerService/GetSellerRating',
            customer__pb2.SessionSellerRequest.SerializeToString,
            customer__pb2.RatingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordSellerFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerService/RecordSellerFeedback',
            customer__pb2.RecordSellerFeedbackRequest.SerializeToString,
            customer__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBuyerPurchases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerService/GetBuyerPurchases',
            customer__pb2.SessionRequest.SerializeToString,
            customer__pb2.PurchaseList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordPurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerService/RecordPurchase',
            customer__pb2.RecordPurchaseRequest.SerializeToString,
            customer__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Barrier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerService/Barrier',
            customer__pb2.BarrierRequest.SerializeToString,
            customer__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
