# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: customer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'customer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ustomer.proto\x12\x08\x63ustomer\":\n\x14\x43reateAccountRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"(\n\x15\x43reateAccountResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"7\n\rLoginResponse\x12\x15\n\rsession_token\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\"\'\n\x0eSessionRequest\x12\x15\n\rsession_token\x18\x01 \x01(\t\"@\n\x0bSessionInfo\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x14\n\x0cprincipal_id\x18\x02 \x01(\x05\x12\x0c\n\x04role\x18\x03 \x01(\t\"@\n\x14SessionSellerRequest\x12\x15\n\rsession_token\x18\x01 \x01(\t\x12\x11\n\tseller_id\x18\x02 \x01(\x05\"8\n\x0eRatingResponse\x12\x11\n\tthumbs_up\x18\x01 \x01(\x05\x12\x13\n\x0bthumbs_down\x18\x02 \x01(\x05\" \n\x0cPurchaseList\x12\x10\n\x08item_ids\x18\x01 \x03(\t\"U\n\x15RecordPurchaseRequest\x12\x15\n\rsession_token\x18\x01 \x01(\t\x12\x10\n\x08item_ids\x18\x02 \x03(\t\x12\x13\n\x0btotal_units\x18\x03 \x01(\x05\"\x07\n\x05\x45mpty2\xee\x03\n\x0f\x43ustomerService\x12P\n\rCreateAccount\x12\x1e.customer.CreateAccountRequest\x1a\x1f.customer.CreateAccountResponse\x12\x38\n\x05Login\x12\x16.customer.LoginRequest\x1a\x17.customer.LoginResponse\x12\x33\n\x06Logout\x12\x18.customer.SessionRequest\x1a\x0f.customer.Empty\x12\x42\n\x0fValidateSession\x12\x18.customer.SessionRequest\x1a\x15.customer.SessionInfo\x12K\n\x0fGetSellerRating\x12\x1e.customer.SessionSellerRequest\x1a\x18.customer.RatingResponse\x12\x45\n\x11GetBuyerPurchases\x12\x18.customer.SessionRequest\x1a\x16.customer.PurchaseList\x12\x42\n\x0eRecordPurchase\x12\x1f.customer.RecordPurchaseRequest\x1a\x0f.customer.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'customer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEACCOUNTREQUEST']._serialized_start=28
  _globals['_CREATEACCOUNTREQUEST']._serialized_end=86
  _globals['_CREATEACCOUNTRESPONSE']._serialized_start=88
  _globals['_CREATEACCOUNTRESPONSE']._serialized_end=128
  _globals['_LOGINREQUEST']._serialized_start=130
  _globals['_LOGINREQUEST']._serialized_end=180
  _globals['_LOGINRESPONSE']._serialized_start=182
  _globals['_LOGINRESPONSE']._serialized_end=237
  _globals['_SESSIONREQUEST']._serialized_start=239
  _globals['_SESSIONREQUEST']._serialized_end=278
  _globals['_SESSIONINFO']._serialized_start=280
  _globals['_SESSIONINFO']._serialized_end=344
  _globals['_SESSIONSELLERREQUEST']._serialized_start=346
  _globals['_SESSIONSELLERREQUEST']._serialized_end=410
  _globals['_RATINGRESPONSE']._serialized_start=412
  _globals['_RATINGRESPONSE']._serialized_end=468
  _globals['_PURCHASELIST']._serialized_start=470
  _globals['_PURCHASELIST']._serialized_end=502
  _globals['_RECORDPURCHASEREQUEST']._serialized_start=504
  _globals['_RECORDPURCHASEREQUEST']._serialized_end=589
  _globals['_EMPTY']._serialized_start=591
  _globals['_EMPTY']._serialized_end=598
  _globals['_CUSTOMERSERVICE']._serialized_start=601
  _globals['_CUSTOMERSERVICE']._serialized_end=1095
# @@protoc_insertion_point(module_scope)
