# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.proto import product_pb2 as product__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in product_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductServiceStub(object):
    """-------------------------------------------------
    Product Service Definition
    -------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterItem = channel.unary_unary(
                '/product.ProductService/RegisterItem',
                request_serializer=product__pb2.RegisterItemRequest.SerializeToString,
                response_deserializer=product__pb2.RegisterItemResponse.FromString,
                _registered_method=True)
        self.ChangePrice = channel.unary_unary(
                '/product.ProductService/ChangePrice',
                request_serializer=product__pb2.ChangePriceRequest.SerializeToString,
                response_deserializer=product__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateQuantity = channel.unary_unary(
                '/product.ProductService/UpdateQuantity',
                request_serializer=product__pb2.UpdateQuantityRequest.SerializeToString,
                response_deserializer=product__pb2.Empty.FromString,
                _registered_method=True)
        self.DisplayItemsForSale = channel.unary_unary(
                '/product.ProductService/DisplayItemsForSale',
                request_serializer=product__pb2.SessionRequest.SerializeToString,
                response_deserializer=product__pb2.ItemList.FromString,
                _registered_method=True)
        self.SearchItems = channel.unary_unary(
                '/product.ProductService/SearchItems',
                request_serializer=product__pb2.SearchRequest.SerializeToString,
                response_deserializer=product__pb2.ItemList.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/product.ProductService/GetItem',
                request_serializer=product__pb2.ItemRequest.SerializeToString,
                response_deserializer=product__pb2.ItemResponse.FromString,
                _registered_method=True)
        self.AddToCart = channel.unary_unary(
                '/product.ProductService/AddToCart',
                request_serializer=product__pb2.CartRequest.SerializeToString,
                response_deserializer=product__pb2.Empty.FromString,
                _registered_method=True)
        self.RemoveFromCart = channel.unary_unary(
                '/product.ProductService/RemoveFromCart',
                request_serializer=product__pb2.CartRequest.SerializeToString,
                response_deserializer=product__pb2.Empty.FromString,
                _registered_method=True)
        self.SaveCart = channel.unary_unary(
                '/product.ProductService/SaveCart',
                request_serializer=product__pb2.SessionRequest.SerializeToString,
                response_deserializer=product__pb2.Empty.FromString,
                _registered_method=True)
        self.ClearCart = channel.unary_unary(
                '/product.ProductService/ClearCart',
                request_serializer=product__pb2.SessionRequest.SerializeToString,
                response_deserializer=product__pb2.Empty.FromString,
                _registered_method=True)
        self.GetCart = channel.unary_unary(
                '/product.ProductService/GetCart',
                request_serializer=product__pb2.SessionRequest.SerializeToString,
                response_deserializer=product__pb2.CartResponse.FromString,
                _registered_method=True)
        self.ProvideFeedback = channel.unary_unary(
                '/product.ProductService/ProvideFeedback',
                request_serializer=product__pb2.FeedbackRequest.SerializeToString,
                response_deserializer=product__pb2.Empty.FromString,
                _registered_method=True)
        self.FinalizePurchase = channel.unary_unary(
                '/product.ProductService/FinalizePurchase',
                request_serializer=product__pb2.SessionRequest.SerializeToString,
                response_deserializer=product__pb2.PurchaseResult.FromString,
                _registered_method=True)


class ProductServiceServicer(object):
    """-------------------------------------------------
    Product Service Definition
    -------------------------------------------------

    """

    def RegisterItem(self, request, context):
        """-------- Seller APIs --------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangePrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateQuantity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplayItemsForSale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItems(self, request, context):
        """-------- Buyer Product APIs --------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToCart(self, request, context):
        """-------- Cart APIs --------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFromCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProvideFeedback(self, request, context):
        """-------- Feedback --------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizePurchase(self, request, context):
        """-------- Purchase --------

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterItem,
                    request_deserializer=product__pb2.RegisterItemRequest.FromString,
                    response_serializer=product__pb2.RegisterItemResponse.SerializeToString,
            ),
            'ChangePrice': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangePrice,
                    request_deserializer=product__pb2.ChangePriceRequest.FromString,
                    response_serializer=product__pb2.Empty.SerializeToString,
            ),
            'UpdateQuantity': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateQuantity,
                    request_deserializer=product__pb2.UpdateQuantityRequest.FromString,
                    response_serializer=product__pb2.Empty.SerializeToString,
            ),
            'DisplayItemsForSale': grpc.unary_unary_rpc_method_handler(
                    servicer.DisplayItemsForSale,
                    request_deserializer=product__pb2.SessionRequest.FromString,
                    response_serializer=product__pb2.ItemList.SerializeToString,
            ),
            'SearchItems': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItems,
                    request_deserializer=product__pb2.SearchRequest.FromString,
                    response_serializer=product__pb2.ItemList.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=product__pb2.ItemRequest.FromString,
                    response_serializer=product__pb2.ItemResponse.SerializeToString,
            ),
            'AddToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToCart,
                    request_deserializer=product__pb2.CartRequest.FromString,
                    response_serializer=product__pb2.Empty.SerializeToString,
            ),
            'RemoveFromCart': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFromCart,
                    request_deserializer=product__pb2.CartRequest.FromString,
                    response_serializer=product__pb2.Empty.SerializeToString,
            ),
            'SaveCart': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCart,
                    request_deserializer=product__pb2.SessionRequest.FromString,
                    response_serializer=product__pb2.Empty.SerializeToString,
            ),
            'ClearCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCart,
                    request_deserializer=product__pb2.SessionRequest.FromString,
                    response_serializer=product__pb2.Empty.SerializeToString,
            ),
            'GetCart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCart,
                    request_deserializer=product__pb2.SessionRequest.FromString,
                    response_serializer=product__pb2.CartResponse.SerializeToString,
            ),
            'ProvideFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvideFeedback,
                    request_deserializer=product__pb2.FeedbackRequest.FromString,
                    response_serializer=product__pb2.Empty.SerializeToString,
            ),
            'FinalizePurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizePurchase,
                    request_deserializer=product__pb2.SessionRequest.FromString,
                    response_serializer=product__pb2.PurchaseResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'product.ProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('product.ProductService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductService(object):
    """-------------------------------------------------
    Product Service Definition
    -------------------------------------------------

    """

    @staticmethod
    def RegisterItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/RegisterItem',
            product__pb2.RegisterItemRequest.SerializeToString,
            product__pb2.RegisterItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangePrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/ChangePrice',
            product__pb2.ChangePriceRequest.SerializeToString,
            product__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateQuantity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/UpdateQuantity',
            product__pb2.UpdateQuantityRequest.SerializeToString,
            product__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisplayItemsForSale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/DisplayItemsForSale',
            product__pb2.SessionRequest.SerializeToString,
            product__pb2.ItemList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/SearchItems',
            product__pb2.SearchRequest.SerializeToString,
            product__pb2.ItemList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/GetItem',
            product__pb2.ItemRequest.SerializeToString,
            product__pb2.ItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/AddToCart',
            product__pb2.CartRequest.SerializeToString,
            product__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFromCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/RemoveFromCart',
            product__pb2.CartRequest.SerializeToString,
            product__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/SaveCart',
            product__pb2.SessionRequest.SerializeToString,
            product__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/ClearCart',
            product__pb2.SessionRequest.SerializeToString,
            product__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/GetCart',
            product__pb2.SessionRequest.SerializeToString,
            product__pb2.CartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProvideFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/ProvideFeedback',
            product__pb2.FeedbackRequest.SerializeToString,
            product__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalizePurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductService/FinalizePurchase',
            product__pb2.SessionRequest.SerializeToString,
            product__pb2.PurchaseResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
